config/routes.rb
Rails.application.routes.draw do


  get 'users/new', to: "users#new", as: 'new_user'
  get 'users/:id', to: "users#show", as: 'user'
  post 'users/:id', to: "users#create"

  get 'calendar/new', to: "calendars#new"
  post 'calendars/:id', to: "calendars#create"
  get 'calendars/:id', to: "calendars#show", as: 'calendar'

  # get 'events_calendars/new', to: "events_calendars#new", as: 'new_event_calendar'
  post 'events_calendars/:id', to: "events_calendars#create", as: 'new_event_calendar'

  get "/", to: "events#home", as: "home"
  get 'events/', to: "events#index", as: 'events'
  get 'events/search', to: "events#search", as: 'search_event'
  get 'events/:id', to: "events#show", as: 'event'

  get 'login', to: 'sessions#new', as: 'login'
  post 'sessions', to: 'sessions#create', as: 'sessions'
  delete 'sessions', to: 'sessions#destroy', as: 'delete_session'

  delete 'events_calendars/:id', to: 'events_calendars#destroy', as: 'delete_event_calendar'



  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
    has_many :events, through: :event_calendars
    belongs_to :user

end

app/models/category.rb
class Category < ApplicationRecord
    
end

app/models/event.rb
class Event < ApplicationRecord



end

app/models/event_calendar.rb
class EventCalendar < ApplicationRecord
    belongs_to :calendar
    belongs_to :event

    validates :calendar_id, uniqueness: { scope: :event_id }


    def start_time
        self.event.date.rfc2822.slice(0, self.event.date.rfc2822.length-15) ##Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_one :calendar

    has_secure_password
    validates :username, uniqueness: { case_sensitive: false }, presence: true

    def full_name
        "#{self.first_name} #{self.last_name}"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :logged_in?

  
    def current_user
      if session[:user_id]
        User.find(session[:user_id])
      end
    end
  
    def logged_in?
      !!current_user
    end
  
    def authorized
      redirect_to login_path unless logged_in?
    end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :authorized, only: [:calendar]

  def new
    @calendar = Calendar.new
  end

  def create
    @calendar = Calendar.create(cal_params)
    if @calendar.save
      redirect_to calendar_path(@calendar)
    else
      redirect_to login_path
    end 
  end

  def show
    @calendar = Calendar.find(params[:id])
    @my_events = EventCalendar.all.select do |event_cal|
      event_cal.calendar.id == @calendar.id
    end
  end

  

  private

  def cal_params
    params.require(:calendar).permit(:user_id)
  end
end

app/controllers/events_calendars_controller.rb
class EventsCalendarsController < ApplicationController

    def create
        @user = current_user
        @calendar = Calendar.find_by(id: @user.calendar.id)
        @event = Event.find(params[:id])
        @eventcalendar = EventCalendar.new(calendar_id: @calendar.id, event_id: @event.id)
        if @eventcalendar.save
            redirect_to calendar_path(@calendar)
        else
            flash.alert = ["This event is already on your Concert Cal"]
            redirect_to events_path
        end
    end

    def destroy
        @user = current_user
        @calendar = Calendar.find_by(id: @user.calendar.id)
        @event = Event.find(params[:id])
        @eventcalendar = EventCalendar.find_by(calendar_id: @calendar.id, event_id: @event.id)
        @eventcalendar.destroy
        redirect_to calendar_path(@calendar)
    end


  end

app/controllers/events_controller.rb
require 'bundler'
Bundler.require
require 'byebug'
require 'time'


class EventsController < ApplicationController

  ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: 'db/development.sqlite3')

  before_action :authorized, only: [:index]
  
  def home 
    
  end

  def index
    json = JSON.parse(RestClient.get 'https://app.ticketmaster.com/discovery/v2/events.json?classificationName=music&marketId=35&apikey=9Gi3bYz1RDWYyebA5yy6setBUgOQPG12&size=50')

    @events = []

    json["_embedded"]["events"].each do |main|
      @events << Event.find_or_create_by(
        artist: main["name"], 
        venue: main["_embedded"]["venues"].first["name"], 
        date: Time.parse(main["dates"]["start"]["localDate"]), 
        image: main["images"][1]["url"], ticket_url: main["url"],
        genre: main["classifications"].first["genre"]["name"]
      )
    end


    @events = Event.order('date ASC')

    @categories = Category.all

  end


  def search
    if params[:search].blank?
      redirect_to events_path
    else
      @parameter = params[:search]
      @category = params[:category][:cat_id]

      if @category == "1"
        @selected_events = Event.all.where("lower(artist) LIKE :search", search: "%#{@parameter}%")
      elsif @category == "2"
        @selected_events = Event.all.where("lower(venue) LIKE :search", search: "%#{@parameter}%")
      elsif @category == "3"
        @selected_events = Event.all.where("lower(genre) LIKE :search", search: "%#{@parameter}%")
      end
    end
  end

  def show
    @event = Event.find(params[:id])
  end
  

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
  
    def create
      user = User.find_by(username: params[:username])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        flash.notice = "Welcome to Concert Cal, #{user.first_name}!"
        redirect_to events_path
      else
        flash.alert = ["Incorrect username or password"]
        redirect_to login_path
      end
    end
  
    def destroy
      session[:user_id] = nil
      redirect_to home_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      Calendar.create(user_id: @user.id)
      redirect_to login_path
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/calendars/show.html.erb
<head>
    <link href="https://fonts.googleapis.com/css?family=Catamaran:400,700|Quicksand&display=swap" rel="stylesheet">
</head>

<h1 class="title"><%="#{@calendar.user.first_name}'s Concert Cal"%></h1>



<%= month_calendar events: @my_events do |date, events| %>
    <%= date.day %>
    <% events.each do |event| %>
      <div>
        <%= link_to event.event.artist, event_path(event.event) %><br>
        <% if session[:user_id] == @calendar.user.id %>
          <%= link_to "Delete from Calendar", delete_event_calendar_path(event.event.id), method: :delete, class: "btn btn-primary btn-sm" %>
        <% end %>
      </div>
    <% end %>
  <% end %>

app/views/events/home.html.erb
<head>
    <link href="https://fonts.googleapis.com/css?family=Catamaran:400,700|Quicksand&display=swap" rel="stylesheet">
</head>

<div class="home">

<div class="centered-left">
    Your concert plans deserve better<br>
    <%= link_to "Get Started", login_path, class: "btn bg-transparent btn-outline-secondary"%>
</div>

</div>

app/views/events/index.html.erb
<head>
    <link href="https://fonts.googleapis.com/css?family=Catamaran:400,700|Quicksand&display=swap" rel="stylesheet">
</head>

<div class="flash">
    <% if flash[:notice] %>
        <%= flash.notice %>
    <% end %>
</div>

<h1 class = "title">EVENTS</h1>


<div class="card">
    <div class="card-body" id="event_search">
        <%= form_tag(search_event_path, method: "get") do %>
            Search by: <%= collection_select(:category, :cat_id, @categories, :id, :name, prompt: true) %> 
            <%= search_field_tag :search, params[:search], placeholder: "Search"%>
            <%= button_tag "Search", :name => nil %><br>
        <% end %>
    </div>
</div>


<% @events.each do |event| %>
    <div class="card">
        <div class="card-header">
            <strong class="card-title"><%=event.artist.upcase%></strong><br>
        </div>
        <div class="row">
            <div class="col-8 align-middle" id = "event_body">
                <span style="font-weight:700">Venue:</span> <%=event.venue%><br>
                <b>Date:</b> <%=event.date.rfc2822.slice(0, event.date.rfc2822.length-15)%><br>
                <br>

                <%= link_to "View Event", event_path(event), class: "btn btn-sm btn-outline-secondary"%><br>
                <%= link_to "Add Event to my Cal", new_event_calendar_path(event), method: :post, class: "btn btn-outline-success", id: "event_button" %><br>
                </div>
            <div class="col">
                <img src =<%=event.image%> width="280" height="190" class="shadow rounded" preserveAspectRatio="xMidYMid slice">
            </div>
        </div>
    </div>
<% end %>




  

app/views/events/search.html.erb
<head>
    <link href="https://fonts.googleapis.com/css?family=Catamaran:400,700|Quicksand&display=swap" rel="stylesheet">
</head>

<h4 class="search-title">Events matching <%=Category.find(@category).name%>: <%=@parameter%><h4><hr>



<% @selected_events.order('date ASC').each do |result| %>
    <div class="card">
        <div class="card-header">
            <strong class="card-title"><%=result.artist.upcase%></strong><br>
        </div>
        <div class="row">
            <div class="col-8 align-middle" id = "event_body">
                <span style="font-weight:700">Venue:</span> <%=result.venue%><br>
                <b>Date:</b> <%=result.date.rfc2822.slice(0, result.date.rfc2822.length-15)%><br>
                <br>
                <%= link_to "View Event", event_path(result), class: "btn btn-sm btn-outline-secondary"%><br>
                <%= link_to "Add Event to my Cal", new_event_calendar_path(result), method: :post, class: "btn btn-outline-success", id: "event_button" %><br>
                </div>
            <div class="col">
                <img src =<%=result.image%> width="280" height="190" class="shadow rounded" preserveAspectRatio="xMidYMid slice">
            </div>
        </div>
    </div>
<% end %>

app/views/events/show.html.erb
<head>
    <link href="https://fonts.googleapis.com/css?family=Catamaran:400,700|Quicksand&display=swap" rel="stylesheet"> 
</head>
<div style="font-family: 'Catamaran', sans-serif;">
    <div class="album py-5 bg-light">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <h1 class="title"><%=@event.artist.upcase%></h1>

                    <div class="card-body" id="event_card">
                        <b><h5>Venue:</b> <%=@event.venue%></h3>
                        <b><h5>Date:</b> <%=@event.date.rfc2822.slice(0, @event.date.rfc2822.length-14)%></h3>
                        <b><h5>Genre:</b> <%=@event.genre%></h3>
                    </div>
                <img src =<%=@event.image%> class="bd-placeholder-img card-img-top" preserveAspectRatio="xMidYMid slice"><br>
                <div id="options">
                    <div class="btn-group">
                        <%=link_to "Add Event to my Cal", new_event_calendar_path(@event), method: :post, class: "btn btn-sm btn-outline-secondary" %>
                        <%=link_to "Buy a ticket", @event.ticket_url, class:"btn btn-sm btn-outline-secondary", target: :_blank %><br>
                    </div>
                </div>
                <div class="rsvp">
                <b>RSVPs:</b><br>
                <% User.all.each do |user| %>
        
                    <% if EventCalendar.all.find_by(event_id: @event.id) %>
                        <% if user.calendar.id == (EventCalendar.all.find_by(event_id: @event.id)).calendar_id %>
                            <%= user.full_name %><br>
                            <% if session[:user_id] != user.id %>
                                <%= link_to "View #{user.first_name}'s Concert Cal", calendar_path(user.calendar.id) %>
                            <% end %>
                        <% end %>
                    <% end %>
                <% end %>
                </div>
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>



    </div>
</div>

app/views/layouts/_errors.html.erb
<% if flash[:alert]%>
<div class = "alert alert-danger errors" %>
    <% flash[:alert].each do |message| %>
        <p><%= message %></p>
    <% end %>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<nav class="navbar shadow-sm justify-content-end">
    <h9 style="font-size: 10px">Bailey 'n Matt ™</h9>
</nav>

app/views/layouts/_nav.html.erb
<% if current_page?(:controller => 'events', :action => 'home') %>
    <nav class="navbar shadow-sm sticky-top" style="background-color: #121010;">
    <h3 class="my-0 mr-md-auto font-weight-normal text-white">CONCERT CAL</h3>

<% else %>
    <nav class="navbar shadow-sm sticky-top" style="background-color: #448ec9;">
    <h3 class="my-0 mr-md-auto font-weight-normal text-white">CONCERT CAL</h3>
    <div class="my-2 my-md-0 mr-md-3 d-flex justify-content-between">
        <%= link_to "Browse Events", events_path, class: "btn btn-light text-dark mr-3" %>
            <% if logged_in? %>
                <%= link_to "My Concert Cal", calendar_path(User.find(session[:user_id]).calendar.id), class: "btn btn-light text-dark mr-3" %>
            <% else %>
                <%= link_to "My Concert Cal", login_path, class: "btn btn-light text-dark mr-3" %>
            <% end %>
        <% if logged_in? %>
            <%= link_to "Sign out", delete_session_path, method: :delete, class: "btn btn-light text-dark mr-3" %>
        <% else %>
            <%= link_to "Sign in", login_path, class: "btn btn-light text-dark mr-3" %>
        <% end %>
    </div>
</nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConcertCal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/nav" %>
    <%= render "layouts/errors" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<head>
    <link href="https://fonts.googleapis.com/css?family=Catamaran:500,700|Quicksand&display=swap" rel="stylesheet"> 
</head>
<div style="font-family: 'Catamaran', sans-serif;">
    <div class="album py-5 bg-light">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <h1 align="center" style="margin-top: 20px; font-weight: 500">CREATE AN ACCOUNT</h1>

                    <div class="card-body" id="event_card">
                        <%= form_for :user do |f| %>
                            <%= f.label "First Name: " %>
                            <%= f.text_field :first_name %>
                            <br>
                            <%= f.label "Last Name: " %>
                            <%= f.text_field :last_name %>
                            <br>
                            <%= f.label "Username: " %>
                            <%= f.text_field :username %>
                            <br>
                            <%= f.label "Password: " %>
                            <%= f.password_field :password %>
                            <br>
                            <br>
                            <%= f.submit "Submit" %>
                        <% end %>
                      <br>
                    </div>
                  </div>
                </div>
              </div>    
            <div class="col-md-4"></div>
        </div>
    </div>



    </div>
</div>

app/views/users/show.html.erb
<h1>Welcome to Concert Cal, <%=@user.first_name%> !</h1>